//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.Common.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BillingSystem.Common.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;address&quot; value cannot be empty..
        /// </summary>
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value &apos;address&apos; must have a maximum of {0} characters..
        /// </summary>
        public static string ADDRESS_MAX_LENGTH {
            get {
                return ResourceManager.GetString("ADDRESS_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The billing id cannot be empty..
        /// </summary>
        public static string BILLING_ID_EMPTY {
            get {
                return ResourceManager.GetString("BILLING_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;currency&quot; value cannot be empty..
        /// </summary>
        public static string CURRENCY_EMPTY {
            get {
                return ResourceManager.GetString("CURRENCY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The customer &apos;{0}&apos;  (ID: {1}) not exists on database. Ignoring invoice with number: {2}. .
        /// </summary>
        public static string CUSTOMER_FROM_EXTERNAL_API_NOT_EXISTS {
            get {
                return ResourceManager.GetString("CUSTOMER_FROM_EXTERNAL_API_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;customer_id&quot; value cannot be empty.
        /// </summary>
        public static string CUSTOMER_ID_EMPTY {
            get {
                return ResourceManager.GetString("CUSTOMER_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The customer could not be found..
        /// </summary>
        public static string CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The date cannot be empty..
        /// </summary>
        public static string DATE_EMPTY {
            get {
                return ResourceManager.GetString("DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;due_date&quot; value cannot be empty.
        /// </summary>
        public static string DUE_DATE_EMPTY {
            get {
                return ResourceManager.GetString("DUE_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email address provided is already in use by another customer..
        /// </summary>
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;email&quot; value cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email is invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value &apos;email&apos; must have a maximum of {0} characters..
        /// </summary>
        public static string EMAIL_MAX_LENGTH {
            get {
                return ResourceManager.GetString("EMAIL_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The ID provided is already in use on the platform..
        /// </summary>
        public static string ID_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ID_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;id&apos; value cannot be empty..
        /// </summary>
        public static string ID_EMPTY {
            get {
                return ResourceManager.GetString("ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;invoice_number&quot; value cannot be empty..
        /// </summary>
        public static string INVOICE_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("INVOICE_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;name&quot; value cannot be empty..
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value &apos;name&apos; must have a maximum of {0} characters..
        /// </summary>
        public static string NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The product &apos;{0}&apos;  (ID: {1}) not exists on database. Ignoring invoice with number: {2}. .
        /// </summary>
        public static string PRODUCT_FROM_EXTERNAL_API_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PRODUCT_FROM_EXTERNAL_API_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;product_id&quot; value cannot be empty..
        /// </summary>
        public static string PRODUCT_ID_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The product could not be found..
        /// </summary>
        public static string PRODUCT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PRODUCT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;quantity&quot; value must be greater than zero.
        /// </summary>
        public static string QUANTITY_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("QUANTITY_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The total amount value must be greater than zero..
        /// </summary>
        public static string TOTAL_AMOUNT_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("TOTAL_AMOUNT_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &quot;unit_price&quot; value must be greater than zero..
        /// </summary>
        public static string UNIT_PRICE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("UNIT_PRICE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
